# Generated by Django 5.2.3 on 2025-06-15 22:14

import django.db.models.deletion
import users.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the verification entry', primary_key=True, serialize=False)),
                ('verification_type', models.CharField(choices=[('identity', 'Identity Verification'), ('address', 'Address Verification'), ('professional', 'Professional Certification'), ('educational', 'Educational Verification'), ('background', 'Background Check'), ('business', 'Business Registration'), ('banking', 'Banking Information'), ('other', 'Other Verification')], help_text='Type of verification', max_length=30)),
                ('document_type', models.CharField(choices=[('national_id', 'National ID Card'), ('passport', 'Passport'), ('drivers_license', "Driver's License"), ('voter_id', 'Voter ID Card'), ('aadhaar', 'Aadhaar Card'), ('pan_card', 'PAN Card'), ('utility_bill', 'Utility Bill'), ('bank_statement', 'Bank Statement'), ('rental_agreement', 'Rental Agreement'), ('property_tax', 'Property Tax Receipt'), ('professional_cert', 'Professional Certificate'), ('business_license', 'Business License'), ('employment_contract', 'Employment Contract'), ('tax_document', 'Tax Document'), ('degree', 'Degree Certificate'), ('transcript', 'Academic Transcript'), ('course_completion', 'Course Completion Certificate'), ('other', 'Other Document')], default='other', help_text='Type of document submitted', max_length=30)),
                ('document_url', models.FileField(blank=True, help_text='Uploaded verification document', null=True, upload_to=users.models.verification_document_path)),
                ('document_back_url', models.FileField(blank=True, help_text='Back side of document if applicable', null=True, upload_to=users.models.verification_document_path)),
                ('document_link', models.URLField(blank=True, help_text='External link to verification document', max_length=255, null=True)),
                ('document_number', models.CharField(blank=True, help_text='Document number for reference', max_length=50)),
                ('status', models.CharField(choices=[('unverified', 'Unverified'), ('pending', 'Pending Review'), ('in_progress', 'In Progress'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', help_text='Current status of verification', max_length=20)),
                ('verification_notes', models.TextField(blank=True, help_text='Internal notes about the verification process')),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection if applicable', null=True)),
                ('verified_at', models.DateTimeField(blank=True, help_text='When the verification was approved', null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When the verification expires', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the verification was submitted')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the verification was last updated')),
                ('external_reference_id', models.CharField(blank=True, help_text='Reference ID from external verification service', max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata related to verification', null=True)),
            ],
            options={
                'verbose_name': 'Verification',
                'verbose_name_plural': 'Verifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveConstraint(
            model_name='pass',
            name='unique_user_pass',
        ),
        migrations.RemoveIndex(
            model_name='accesstoken',
            name='users_accesstoken_user_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='accesstoken',
            name='users_accesstoken_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_user_type_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_user_verified_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_user_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_user_rating_idx',
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='pass',
            unique_together={('user_passing', 'user_passed')},
        ),
        migrations.AddField(
            model_name='verification',
            name='user',
            field=models.ForeignKey(help_text='User being verified', on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='verification',
            name='verified_by',
            field=models.ForeignKey(blank=True, help_text='Admin who processed this verification', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifications_processed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='verification',
            unique_together={('user', 'verification_type', 'document_type')},
        ),
    ]
