# Generated by Django 5.2.2 on 2025-06-08 00:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='failed_pin_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='pin',
            field=models.CharField(default=django.utils.timezone.now, help_text='4-digit PIN for authentication (hashed)', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='pin_created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='pin_locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pin_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
