# Generated by Django 5.2.1 on 2025-05-31 23:37

import django.db.models.deletion
import uuid
import verification.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the verification entry', primary_key=True, serialize=False)),
                ('verification_type', models.CharField(choices=[('identity', 'Identity Verification'), ('address', 'Address Verification'), ('professional', 'Professional Certification'), ('educational', 'Educational Verification'), ('background', 'Background Check'), ('business', 'Business Registration'), ('banking', 'Banking Information'), ('other', 'Other Verification')], help_text='Type of verification', max_length=30)),
                ('document_type', models.CharField(choices=[('national_id', 'National ID Card'), ('passport', 'Passport'), ('drivers_license', "Driver's License"), ('voter_id', 'Voter ID Card'), ('aadhaar', 'Aadhaar Card'), ('pan_card', 'PAN Card'), ('utility_bill', 'Utility Bill'), ('bank_statement', 'Bank Statement'), ('rental_agreement', 'Rental Agreement'), ('property_tax', 'Property Tax Receipt'), ('professional_cert', 'Professional Certificate'), ('business_license', 'Business License'), ('employment_contract', 'Employment Contract'), ('tax_document', 'Tax Document'), ('degree', 'Degree Certificate'), ('transcript', 'Academic Transcript'), ('course_completion', 'Course Completion Certificate'), ('other', 'Other Document')], default='other', help_text='Type of document submitted', max_length=30)),
                ('document_url', models.FileField(blank=True, help_text='Uploaded verification document', null=True, upload_to=verification.models.verification_document_path)),
                ('document_back_url', models.FileField(blank=True, help_text='Back side of document if applicable', null=True, upload_to=verification.models.verification_document_path)),
                ('document_number', models.CharField(blank=True, help_text='Document number for reference', max_length=50)),
                ('status', models.CharField(choices=[('unverified', 'Unverified'), ('pending', 'Pending Review'), ('in_progress', 'In Progress'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', help_text='Current status of verification', max_length=20)),
                ('verification_notes', models.TextField(blank=True, help_text='Internal notes about the verification process')),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection if applicable', null=True)),
                ('verified_at', models.DateTimeField(blank=True, help_text='When the verification was approved', null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When the verification expires', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the verification was submitted')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the verification was last updated')),
                ('external_reference_id', models.CharField(blank=True, help_text='Reference ID from external verification service', max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata related to verification', null=True)),
                ('user', models.ForeignKey(help_text='User being verified', on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, help_text='Admin who processed this verification', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifications_processed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Verification',
                'verbose_name_plural': 'Verifications',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'verification_type', 'document_type')},
            },
        ),
    ]
