# Generated by Django 5.2.1 on 2025-06-01 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='verification',
            name='document_link',
            field=models.URLField(blank=True, help_text='External link to verification document', max_length=255, null=True),
        ),
    ]
