# Generated by Django 5.0.1 on 2025-01-28 12:00:00

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
    ] 