# Generated by Django 5.2.2 on 2025-06-11 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'ordering': ['sort_order', 'name'], 'verbose_name_plural': 'Service Categories'},
        ),
        migrations.AlterModelOptions(
            name='servicesubcategory',
            options={'ordering': ['category__sort_order', 'category__name', 'sort_order', 'name'], 'verbose_name_plural': 'Service SubCategories'},
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='icon_url',
            field=models.URLField(blank=True, help_text='External icon URL', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, help_text='Order for displaying categories'),
        ),
        migrations.AddField(
            model_name='servicesubcategory',
            name='icon_url',
            field=models.URLField(blank=True, help_text='External icon URL', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='servicesubcategory',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, help_text='Order for displaying subcategories within category'),
        ),
    ]
