# Generated by Django 5.2.3 on 2025-06-15 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Verification',
        ),
    ]
