# Generated by Django 5.2.3 on 2025-06-22 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_delete_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
