# Generated by Django 5.2.3 on 2025-06-24 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_service_hourly_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicecategory',
            name='icon_url',
        ),
        migrations.RemoveField(
            model_name='servicesubcategory',
            name='icon_url',
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='icon_name',
            field=models.CharField(default='home', help_text='Icon name identifier', max_length=50),
        ),
        migrations.AddField(
            model_name='servicesubcategory',
            name='icon_name',
            field=models.CharField(default='home', help_text='Icon name identifier', max_length=50),
        ),
    ]
