# Generated by Django 5.0.1 on 2025-01-28 12:00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bids', '0001_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AISuggestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('suggestion_type', models.CharField(choices=[('service_improvement', 'Service Improvement'), ('pricing', 'Pricing Recommendation'), ('bid_amount', 'Bid Amount Suggestion'), ('bid_message', 'Bid Message Template'), ('category', 'Category Recommendation'), ('marketing', 'Marketing Tip'), ('general', 'General Suggestion')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('suggested_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('confidence_score', models.FloatField(default=0.5, help_text='Confidence level of the AI for this suggestion (0-1)')),
                ('is_used', models.BooleanField(default=False, help_text='Indicates if the suggestion was used by the user')),
                ('status', models.CharField(choices=[('new', 'New'), ('viewed', 'Viewed'), ('implemented', 'Implemented'), ('rejected', 'Rejected'), ('dismissed', 'Dismissed')], default='new', max_length=20)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True, help_text='User feedback on this suggestion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_suggestions', to='bids.bid')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_suggestions', to='services.servicecategory')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_suggestions', to='services.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_suggestions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Suggestion',
                'verbose_name_plural': 'AI Suggestions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIFeedbackLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('interaction_type', models.CharField(choices=[('view', 'Viewed Suggestion'), ('use', 'Used Suggestion'), ('accept_bid', 'Accepted Bid with Suggestion'), ('complete_booking', 'Completed Booking with Suggestion'), ('feedback', 'Provided Feedback'), ('reject', 'Rejected Suggestion')], max_length=30)),
                ('interaction_data', models.JSONField(blank=True, help_text='Additional data about the interaction', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_feedback_logs', to='bids.bid')),
                ('suggestion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_logs', to='ai_suggestions.aisuggestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_feedback_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Feedback Log',
                'verbose_name_plural': 'AI Feedback Logs',
                'ordering': ['-created_at'],
            },
        ),
    ] 