# Generated by Django 5.2.1 on 2025-01-27 12:00

from django.conf import settings
import django.db.models.deletion
import reviews.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.DecimalField(decimal_places=1, help_text='Overall rating of the service', max_digits=3)),
                ('rating_breakdown', models.JSONField(blank=True, help_text='Detailed breakdown of ratings (e.g., punctuality, quality)', null=True)),
                ('comment', models.TextField(help_text='Text comment of the review')),
                ('is_verified', models.BooleanField(default=False, help_text='Flag indicating if the review is verified')),
                ('is_public', models.BooleanField(default=True, help_text='Whether the review is publicly visible')),
                ('provider_response', models.TextField(blank=True, help_text="Provider's text response to the review", null=True)),
                ('provider_response_date', models.DateTimeField(blank=True, help_text="Timestamp of the provider's response", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(help_text='The booking this review is for', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='bookings.booking')),
                ('client', models.ForeignKey(help_text='Customer who left the review', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(help_text='Service provider being reviewed', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(help_text='The service being reviewed', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='services.service')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(help_text='Image uploaded with the review', upload_to=reviews.models.review_image_path)),
                ('caption', models.CharField(blank=True, help_text='Optional caption for the image', max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='reviews.review')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ] 