# Generated by Django 5.0.1 on 2025-01-28 12:00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bids', '0001_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('booking_date', models.DateField(help_text='Date of the booking')),
                ('start_time', models.TimeField(help_text='Start time of the booking')),
                ('end_time', models.TimeField(help_text='End time of the booking')),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('address', models.TextField(blank=True, help_text='Address where the service will take place', null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Latitude coordinate', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Longitude coordinate', max_digits=9, null=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Total cost of the booking', max_digits=10)),
                ('payment_details', models.JSONField(blank=True, help_text='Details about the payment for this booking', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('disputed', 'Disputed')], default='pending', max_length=20)),
                ('requirements', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, help_text='Rating given for this booking', max_digits=3, null=True)),
                ('review', models.TextField(blank=True, help_text='Text review for this booking', null=True)),
                ('is_rescheduled', models.BooleanField(default=False)),
                ('original_booking_date', models.DateTimeField(blank=True, null=True)),
                ('rescheduled_date', models.DateField(blank=True, help_text='New date if rescheduled', null=True)),
                ('rescheduled_count', models.PositiveSmallIntegerField(default=0)),
                ('rescheduled_reason', models.TextField(blank=True, null=True)),
                ('cancellation_reason', models.CharField(blank=True, choices=[('customer_request', 'Customer Request'), ('provider_unavailable', 'Provider Unavailable'), ('rescheduled', 'Rescheduled to New Date'), ('payment_issue', 'Payment Issue'), ('service_issue', 'Service Issue'), ('other', 'Other Reason')], max_length=50, null=True)),
                ('cancellation_date', models.DateTimeField(blank=True, null=True)),
                ('calendar_event_id', models.CharField(blank=True, help_text='ID of synced calendar event', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='bids.bid')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_bookings', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_bookings', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_bookings', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='services.service')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['-created_at'],
            },
        ),
    ] 