# Generated by Django 5.2.1 on 2025-01-27 12:00

from django.conf import settings
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='product_category_icons/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product Category',
                'verbose_name_plural': 'Product Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the product', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Product name', max_length=200)),
                ('description', models.TextField(help_text='Product description')),
                ('price', models.DecimalField(decimal_places=2, help_text='Product price', max_digits=10)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, help_text='Discounted price if applicable', max_digits=10, null=True)),
                ('product_type', models.CharField(choices=[('physical', 'Physical Product'), ('digital', 'Digital Product'), ('subscription', 'Subscription'), ('packaged_service', 'Packaged Service')], help_text='Type of product', max_length=20)),
                ('stock_quantity', models.IntegerField(default=0, help_text='Available quantity in stock')),
                ('images', models.JSONField(blank=True, default=list, help_text='List of image URLs')),
                ('features', models.JSONField(blank=True, default=list, help_text='List of product features')),
                ('specifications', models.JSONField(blank=True, default=dict, help_text='Product specifications as key-value pairs')),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending Approval'), ('inactive', 'Inactive'), ('out_of_stock', 'Out of Stock')], default='pending', help_text='Current status of the product', max_length=20)),
                ('is_featured', models.BooleanField(default=False, help_text='Whether product is featured in the marketplace')),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, help_text='Average rating for the product', max_digits=3)),
                ('reviews_count', models.PositiveIntegerField(default=0, help_text='Count of reviews for the product')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='Product category', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.productcategory')),
                ('related_service_category', models.ForeignKey(blank=True, help_text='Related service category if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_products', to='services.servicecategory')),
                ('seller', models.ForeignKey(help_text='User selling this product', on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
            },
        ),
    ] 